version: '3'
services:
  es-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: es-node1
    environment:
      - node.name=es-node1
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-node2,es-node3,es-node4
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3,es-node4
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"  # Set heap size to 2 GB
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-net
  es-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: es-node2
    environment:
      - node.name=es-node2
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-node1,es-node3,es-node4
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-net
  es-node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: es-node3
    environment:
      - node.name=es-node3
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-node1,es-node2,es-node4
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-net
  es-node4:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: es-node4
    environment:
      - node.name=es-node4
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-node1,es-node2,es-node3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-net

networks:
  es-net:
    driver: bridge
